### ISSUE TITLE
Publish ABAP Unit code coverage result

### ISSUE THREAD

**Issue by Srinu3366** [trr-official/abapunit2junit#10]
Is it possible to publish ABAP Unit code coverage result in Azure pipelines?

Thanks,
Srini

**Comment by matt1as** [comment]
Yes, definitely, that's how we use it. Here are the steps we use

First npm install to install all node dependencies
```
steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: '$(System.DefaultWorkingDirectory)/_<Repo>/drop/'
    verbose: false
```

then run the script
```
steps:
- script: 'npm start -- --host=<host> --protocol=https --insecure=true --username=<username> --password=<password> --package=<package>'
  workingDirectory: '$(System.DefaultWorkingDirectory)/_<Repo>/drop'
  displayName: 'Run test'
```

Then publish the result
```
steps:
- task: PublishTestResults@2
  displayName: 'Publish Test Results **/result/*.xml'
  inputs:
    testResultsFiles: '**/result/*.xml'
```


I'm sure you don't need to define the working directory, but "if it works don't fix it"
